version: '3.9'

services:
  api-1:
    image: simple-mvc-kotlin
    hostname: api-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlserver:3306/db-rinhabackend?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network
    depends_on:
      mysqlserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'

  api-2:
    image: simple-mvc-kotlin
    hostname: api-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlserver:3306/db-rinhabackend?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network
    depends_on:
      mysqlserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.1GB'

  mysqlserver:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./src/main/resources/scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      app-network:
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot" ]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

networks:
  app-network: