version: '3.9'

services:
  api-1:
    image: simple-mvc-kotlin
    hostname: api-1
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodbserver:27017/rinhabackend
    networks:
      - app-network
    depends_on:
      mongodbserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'

  api-2:
    image: simple-mvc-kotlin
    hostname: api-1
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodbserver:27017/rinhabackend
    networks:
      - app-network
    depends_on:
      mongodbserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.7GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.1GB'

  mongodbserver:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./src/main/resources/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      app-network:
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

networks:
  app-network:
